//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIspričnica
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mydbEntities1 : DbContext
    {
        public mydbEntities1()
            : base("name=mydbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bolnica> bolnica { get; set; }
        public virtual DbSet<ispričnice> ispričnice { get; set; }
        public virtual DbSet<pacijenti> pacijenti { get; set; }
        public virtual DbSet<povijestbolesti> povijestbolesti { get; set; }
        public virtual DbSet<pregledi> pregledi { get; set; }
        public virtual DbSet<prijave> prijave { get; set; }
        public virtual DbSet<razinaprava> razinaprava { get; set; }
        public virtual DbSet<zahtjevi> zahtjevi { get; set; }
        public virtual DbSet<zaposlenici> zaposlenici { get; set; }
    }
}
