//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIspričnica
{
    using System;
    using System.Collections.Generic;
    
    public partial class pacijenti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pacijenti()
        {
            this.pregledi = new HashSet<pregledi>();
            this.zahtjevi = new HashSet<zahtjevi>();
        }
    
        public int idPacijenti { get; set; }
        public string ImePrezime { get; set; }
        public string OIB { get; set; }
        public string BrojPoliceOsiguranja { get; set; }
        public string BrojZdravstveneIskaznice { get; set; }
        public string lozinka { get; set; }
        public long Zaposlenici_idZaposlenici { get; set; }
    
        public virtual zaposlenici zaposlenici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pregledi> pregledi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zahtjevi> zahtjevi { get; set; }
    }
}
