//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIspričnica
{
    using System;
    using System.Collections.Generic;
    
    public partial class povijestbolesti
    {
        public long idPovijestBolesti { get; set; }
        public string Dijagnoza { get; set; }
        public long Pregledi_idPregledi { get; set; }
    
        public virtual pregledi pregledi { get; set; }
    }
}
