//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIspričnica
{
    using System;
    using System.Collections.Generic;
    
    public partial class zahtjevi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zahtjevi()
        {
            this.ispričnice = new HashSet<ispričnice>();
        }
    
        public long idZahtjevi { get; set; }
        public int Pacijenti_idPacijenti { get; set; }
        public string Opis { get; set; }
        public Nullable<System.DateTime> Datum_od { get; set; }
        public Nullable<System.DateTime> Datum_do { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ispričnice> ispričnice { get; set; }
        public virtual pacijenti pacijenti { get; set; }
    }
}
