//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eIspričnica
{
    using System;
    using System.Collections.Generic;
    
    public partial class zaposlenici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zaposlenici()
        {
            this.pacijenti = new HashSet<pacijenti>();
            this.prijave = new HashSet<prijave>();
        }
    
        public long idZaposlenici { get; set; }
        public string ImePrezime { get; set; }
        public string korIme { get; set; }
        public string korLozinka { get; set; }
        public long RazinaPrava_idRazinaPrava { get; set; }
        public long Bolnica_idBolnica { get; set; }
    
        public virtual bolnica bolnica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pacijenti> pacijenti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prijave> prijave { get; set; }
        public virtual razinaprava razinaprava { get; set; }
        public virtual bolnica imeBolnice { get; set; }
    }
}
